# permissions for end users to view rollingmonitor12s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingmonitor12-viewer-role
rules:
- apiGroups:
  - demo.transwarp.io
  resources:
  - rollingmonitor12s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.transwarp.io
  resources:
  - rollingmonitor12s/status
  verbs:
  - get
