# permissions for end users to edit rollingmonitor12s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingmonitor12-editor-role
rules:
- apiGroups:
  - demo.transwarp.io
  resources:
  - rollingmonitor12s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.transwarp.io
  resources:
  - rollingmonitor12s/status
  verbs:
  - get
